Repository vyomea/CMPUT404-project-socialdistribution, pull requests merged in 2022-02, with the labels that each got.

#46 chore: add dev db and added a couple models
  .devcontainer/docker-compose.yml
  .env.TEMPLATE
  .github/workflows/test.yaml
  src/server/babel.config.js
  src/server/package-lock.json
  src/server/package.json
  src/server/src/app.ts
  src/server/src/db.ts
  src/server/src/models/Author.ts
  src/server/src/models/Post.ts
Labels: backend

#47 Screen Mockups
  screen_mockups.pdf
Labels: documentation

#53 Homepage
  .gitignore
  src/app/package-lock.json
  src/app/package.json
  src/app/src/App.tsx
  src/app/src/components/Logo.tsx
  src/app/src/components/NavBar.tsx
  src/app/src/pages/Homepage.tsx
  src/app/tsconfig.json
Labels: frontend

#57 chore(testing): frontend setup and test components
  src/app/jest.config.js
  src/app/package-lock.json
  src/app/package.json
  src/app/src/App.test.tsx
  src/app/src/components/NavBar.tsx
  src/app/src/components/__tests__/Logo.test.tsx
  src/app/src/components/__tests__/NavBar.test.tsx
  src/app/src/components/__tests__/__snapshots__/Logo.test.tsx.snap
  src/app/src/globals.d.ts
  src/app/src/pages/__tests__/Homepage.test.tsx
  src/app/src/pages/__tests__/__snapshots__/Homepage.test.tsx.snap
  src/app/tsconfig.json
Labels: frontend

#63 GitHub component
  src/app/package-lock.json
  src/app/package.json
  src/app/src/components/Activity.tsx
  src/app/src/components/Github.tsx
  src/app/src/utils/GithubUtils.ts
Labels: frontend
