Repository vyomea/CMPUT404-project-socialdistribution, pull requests merged in 2022-03, with the labels that each got.

#64 Implement access to API on frontend
  src/app/package-lock.json
  src/app/package.json
  src/app/src/api/api.ts
  src/app/src/api/models/Author.ts
  src/app/src/api/models/Comment.ts
  src/app/src/api/models/Like.ts
  src/app/src/api/models/Post.ts
Labels: frontend

#65 Admin Page Layout
  src/app/src/components/AdminAuthorCard.tsx
  src/app/src/components/AdminNodeCard.tsx
  src/app/src/components/AdminPostCard.tsx
  src/app/src/components/AdminRequestCard.tsx
  src/app/src/pages/Admin.tsx
Labels: frontend

#67 Add react-router-dom and some routes
  src/app/package-lock.json
  src/app/package.json
  src/app/src/App.tsx
  src/app/src/pages/Error.tsx
  src/app/src/pages/Homepage.tsx
  src/app/src/pages/Mainpage.tsx
  src/app/src/pages/Profile.tsx
Labels: frontend

#70 Set up CORS
  src/app/src/api/api.ts
  src/server/package-lock.json
  src/server/package.json
  src/server/src/app.ts
Labels: frontend, backend

#72 Implement login and reigstration on frontend, API improvements and fixes
  src/app/package-lock.json
  src/app/package.json
  src/app/src/App.tsx
  src/app/src/api/api.ts
  src/app/src/pages/Homepage.tsx
  src/app/src/pages/SignIn.tsx
  src/app/src/pages/SignUp.tsx
  src/app/src/pages/__tests__/Homepage.test.tsx
  src/app/src/pages/__tests__/SignIn.test.tsx
  src/app/src/pages/__tests__/SignUp.test.tsx
  src/app/src/pages/__tests__/__snapshots__/Homepage.test.tsx.snap
  src/app/src/pages/__tests__/__snapshots__/SignIn.test.tsx.snap
  src/app/src/pages/__tests__/__snapshots__/SignUp.test.tsx.snap
  src/server/src/app.ts
  src/server/src/controllers/auth.controllers.ts
  src/server/src/controllers/author.controllers.ts
  src/server/src/controllers/post.controllers.ts
  src/server/src/handlers/auth.handlers.ts
  src/server/src/routes/author.routes.ts
  src/server/src/types/auth.ts
Labels: frontend, backend

#73 Basic Frontend Connections
  src/app/src/App.tsx
  src/app/src/components/AdminAuthorCard.tsx
  src/app/src/components/AdminPostCard.tsx
  src/app/src/pages/Admin.tsx
  src/app/src/pages/Mainpage.tsx
  src/app/src/pages/Profile.tsx
  src/app/src/pages/__tests__/Mainpage.test.tsx
  src/app/src/pages/__tests__/Profile.test.tsx
  src/app/src/pages/__tests__/__snapshots__/Mainpage.test.tsx.snap
  src/app/src/pages/__tests__/__snapshots__/Profile.test.tsx.snap
Labels: frontend

#78 Fix: edit category
  src/app/src/components/Edit.tsx
Labels: frontend

#79 Prevent app from rendering before current user is fetched from server
  src/app/src/App.tsx
  src/app/src/pages/Mainpage.tsx
Labels: frontend

#80 Add isAdmin field to Author model and utility for creating admin accounts
  src/app/src/api/models/Author.ts
  src/app/src/pages/__tests__/Mainpage.test.tsx
  src/app/src/pages/__tests__/Profile.test.tsx
  src/server/package-lock.json
  src/server/package.json
  src/server/src/controllers/author.controllers.ts
  src/server/src/create-admin.ts
  src/server/src/models/Author.ts
Labels: backend

#83 Conditional Buttons + ProfileImages
  src/app/src/components/Add.tsx
  src/app/src/components/AdminAuthorCard.tsx
  src/app/src/components/Edit.tsx
  src/app/src/components/UserPost.tsx
  src/app/src/pages/Admin.tsx
  src/app/src/pages/Mainpage.tsx
  src/app/src/pages/Profile.tsx
Labels: frontend

#90 Admin nodes
  src/app/src/api/api.ts
  src/app/src/api/models/Node.ts
  src/app/src/components/AddNode.tsx
  src/app/src/components/AdminNodeCard.tsx
  src/app/src/pages/Admin.tsx
Labels: frontend

#87 Admin Authors
  src/app/src/App.tsx
  src/app/src/api/api.ts
  src/app/src/api/models/Author.ts
  src/app/src/components/AddAuthor.tsx
  src/app/src/components/AdminAuthorCard.tsx
  src/app/src/components/EditAuthor.tsx
  src/app/src/components/UserPost.tsx
  src/app/src/pages/Admin.tsx
  src/app/src/pages/Profile.tsx
  src/server/src/models/Author.ts
Labels: frontend

#95 Admin Post Filtering
  src/app/src/pages/Admin.tsx
Labels: frontend

#98 Improvements to backend controllers and tests
  src/server/__tests__/routes/auth_endpoint.test.ts
  src/server/__tests__/routes/authors_endpoint.test.ts
  src/server/__tests__/routes/posts_endpoint.test.ts
  src/server/__tests__/routes/sample_endpoint.test.ts
  src/server/__tests__/sample.test.js
  src/server/package.json
  src/server/src/controllers/auth.controllers.ts
  src/server/src/controllers/author.controllers.ts
  src/server/src/controllers/comment.controllers.ts
  src/server/src/controllers/post.controllers.ts
  src/server/src/db.ts
  src/server/src/handlers/auth.handlers.ts
  src/server/src/routes/auth.routes.ts
  src/server/src/setup-db.ts
  src/server/src/utilities/pick.ts
Labels: backend, testing
